### ISSUE TITLE
[BUGFIX] Make Workflow Queries compatible with sql_mode=ONLY_FULL_GROUP_BY

### ISSUE THREAD

**Issue by vertexvaar** [in2code-de/in2publish_core#1]
Inspect problem with sql_mode=ONLY_FULL_GROUP_BY and page tree Workflow colors

When mysqld SQL mode ONLY_FULL_GROUP_BY is enable the page tree might not render due to an erroneous or incomplete sql statement.
More information is needed to reproduce this problem and, of course, time to fix that ;)

For now you should just be fine with disabling that option.

Error:

```
Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'temp_table.identifier' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

**Comment by einpraegsam** [comment]
Why should we take the time to rebuild the already working queries? As you may know we spent a lot of time in this stuff (Performance & Co.).

**Comment by vertexvaar** [comment]
This is not about rebuilding the query, it's about investigation. And since the Pagetree crashes completely the query is _not_ working.
I'm quite sure that we just have to add a select field...

**Comment by einpraegsam** [comment]
ok, we can invest some minutes into this

**Comment by vertexvaar** [comment]
Just realized that this is the wrong repository. Will reopen the issue in https://github.com/in2code-de/in2publish/issues
