### ISSUE TITLE
Apache = hard requirement?

### ISSUE THREAD

**Issue by boristimp** [in2code-de/in2publish_core#10]
According to the docs (https://github.com/in2code-de/in2publish_core/blob/master/Documentation/Installation/Preparation.md) Apache is needed - just asking before evaluating a setup, did you try a setup using NGINX together with the respective ssh modules as well?

**Comment by vertexvaar** [comment]
We didn't test it with nginx, nor do i know anyone that tried this before.
Since we don't rely on specific apache modules, just on PHP extensions like php-ssh2, it should work anyway. I would appreciate any feedback ;)

**Comment by einpraegsam** [comment]
Meanwhile there was some feedback from another user in Slack channel ext-in2publish: "We use it on an nginx. works"
