### ISSUE TITLE
invalid XML in german language file

### ISSUE THREAD

**Issue by pi-phi** [in2code-de/in2publish_core#103]
trying to use 11.0.6  breaks the BE if using the German BackEnd:

`The path provided does not point to an existing and accessible well-formed XML file. Reason: expected '>' in ...../typo3conf/ext/in2publish_core/Resources/Private/Language/de.locallang.xlf, line 30`

A `>` is missing in the master-v11 branch.

**Comment by tinzog** [comment]
Thank you for notifying about this issue. The problem has been solved in tag 11.0.7
