### ISSUE TITLE
SimplifiedOverviewAndPublishing throws 503 "Call to a member function addRelatedRecord() on null"

### ISSUE THREAD

**Issue by YKWeyer** [in2code-de/in2publish_core#105]
**Versions**: TYPO3 `11.5.31`, in2publish `11.2.1`, in2publish_core `11.0.7`

When using `SimplifiedOverviewAndPublishing`, opening the Content Publisher overview module returns a 503 error for specific pages with the following error message:

> Call to a member function addRelatedRecord() on null

It seems to happens in the ShallowRecordFinder in the `addChildPagesRecursively` method, on [line 287 (`$pageRecords[$pid]->addRelatedRecord($record);`)](https://github.com/in2code-de/in2publish_core/blob/050aebbdcd8333f11cb2882007c35d69da2fec86/Classes/Features/SimplifiedOverviewAndPublishing/ShallowRecordFinder.php#L287)

My guess is, sometimes the translations will be delivered by the database _before_ the origin records, since they all have the same `sorting` value (used by `SingleDatabaseRepository::findByProperty`). For example in our pages table, when looking for records under a specific `pid` and using the `sorting` column to order results, the translation with uid `61483` will come after its parent record `75`:

![image](https://github.com/in2code-de/in2publish_core/assets/1093360/aefa9db1-18b7-40d8-ba78-22d98fc677a9)

But the loop expects the origin for translations (used as `$pid`) to be already in the `$pageRecords` array. A possible workaround would be to add the `languageField` as an additional (asc) order field in `SingleDatabaseRepository::findByProperty`:

```patch
         if (!empty($GLOBALS['TCA'][$table]['ctrl']['sortby'])) {
             $query->orderBy($GLOBALS['TCA'][$table]['ctrl']['sortby']);
         } elseif (!empty($GLOBALS['TCA'][$table]['ctrl']['default_sortby'])) {
             $orderByClauses = QueryHelper::parseOrderBy($GLOBALS['TCA'][$table]['ctrl']['default_sortby']);
             foreach ($orderByClauses as $orderByClause) {
                 if (!empty($orderByClause[0])) {
                     $query->addOrderBy($orderByClause[0], $orderByClause[1]);
                 }
             }
         } else {
             $query->orderBy('uid');
         }

+        if (!empty($GLOBALS['TCA'][$table]['ctrl']['languageField'])) {
+            $query->addOrderBy($GLOBALS['TCA'][$table]['ctrl']['languageField']);
+        }
+

         $result = $query->execute();
```

That being said, I am a little unsure, since I assume this issue would affect most of the multilingual websites, and I am wondering why it didn't surface until now. Maybe it's an edge case that only happens in our setup?

**Comment by sbusemann** [comment]
Planned for team: https://projekte.in2code.de/issues/59565

**Comment by dhoffmann1979** [comment]
PR is merged into develop-v11
