### ISSUE TITLE
Resolver: additionalWhere is case-sensitive

### ISSUE THREAD

**Issue by YKWeyer** [in2code-de/in2publish_core#112]
[Resolvers](https://github.com/in2code-de/in2publish_core/tree/7e7032a6df2e67c6e5e468c7760c7a1202abcfb1/Classes/Component/Core/Resolver) check `additionalWhere` and remove the leading `AND` if there is any, for example:

https://github.com/in2code-de/in2publish_core/blob/7e7032a6df2e67c6e5e468c7760c7a1202abcfb1/Classes/Component/Core/Resolver/InlineSelectResolver.php#L47-L49

Unfortunately, extensions don't always use uppercase in their `foreign_table_where` instructions, e.g.  https://github.com/in2code-de/powermail/blob/db37b606e0021d4cb85abd96a50e505f5f4373e3/Configuration/TCA/tx_powermail_domain_model_page.php#L58

This leads to an exception in the back-end when calling the Overview Module for folders with Powermail forms:

> (1/2) Doctrine\DBAL\Exception\SyntaxErrorException
>
> An exception occurred while executing 'SELECT * FROM `tx_powermail_domain_model_page` WHERE (`uid` IN (?, ?, ?, ?, ?, ?, ?)) AND (and tx_powermail_domain_model_page.pid=6172 AND tx_powermail_domain_model_page.sys_language_uid IN (-1,0)) ORDER BY `sorting` ASC' with params [194, 201, 205, 204, 197, 206, 199]: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'and tx_powermail_domain_model_page.pid=6172 AND tx_powermail_domain_model_pag...' at line 1

(Notice the `AND (and` part)

This could be solved by either always uppercasing the first argument of `str_starts_with`, or using `stripos` to perform the check:

```php
 if (str_starts_with(strtoupper($additionalWhere), 'AND ')) {
     $additionalWhere = trim(substr($additionalWhere, 4)); 
 } 
```
or

```php
 if (stripos($additionalWhere, 'AND ') === 0) {
     $additionalWhere = trim(substr($additionalWhere, 4)); 
 } 
```

Let me know whichever suits you the best, and I can open a MR with the suggested changes :smiley:

**Comment by YKWeyer** [comment]
TYPO3 actually provides a native helper to perform such a removal: `QueryHelper::stripLogicalOperatorPrefix`

https://github.com/TYPO3/typo3/blob/193635170fdc4eb5fdb357de12c4b949db115fc3/typo3/sysext/core/Classes/Database/Query/QueryHelper.php#L171-L174

Maybe it would make sense to always call the core helper, without wrapping it in in a check?

**Comment by vertexvaar** [comment]
Thank you for reporting this issue. I fixed all occurrences of the stripping.
