### ISSUE TITLE
Support REDIRECT_IN2PUBLISH_CONTEXT env var

### ISSUE THREAD

**Issue by jousch** [in2code-de/in2publish_core#12]
In some environments (where you just can set env vars within htaccess) the env var `IN2PUBLISH_CONTEXT` get's prefixed with `REDIRECT_` 😡

I saw that this also supports the TYPO3 core 😵

**Comment by vertexvaar** [comment]
@jousch can you provide more information about your environment? Have you tried setting the context via `SetnEnv` or do you do some mod_rewrite voodoo?

**Comment by jousch** [comment]
Sorry, no voodoo ;)

`echo "SetEnv IN2PUBLISH_CONTEXT Local" >> ~/public_html/web/.htaccess` It seems like, that some servers has such a prefixing. The server is afaik a (managed vserver at hetzner). See https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/Core/Bootstrap.php#L117

**Comment by vertexvaar** [comment]
i think your PR would solve the issue, but instead of

```
if (false === ($environmentVariable = getenv(static::ENV_VAR_NAME) || getenv('REDIRECT_' . static::ENV_VAR_NAME))) {
```
try something like

```
$environmentVariable = getenv(static::ENV_VAR_NAME) ?: getenv('REDIRECT_' . static::ENV_VAR_NAME ?: false;
if (false === $environmentVariable) {
```

(not tested)
