### ISSUE TITLE
local DB test fails (TYPO3 8.7.0-dev)

### ISSUE THREAD

**Issue by jousch** [in2code-de/in2publish_core#14]
In TYPO3 dev-master `isConnected` is always `false`.

I would suggest to in a first step to fix this with `$localDatabase->connectDB();` before returning the error message: `return new TestResult('database.local_offline', TestResult::ERROR);`

(`https://github.com/in2code-de/in2publish_core/blob/master/Classes/Testing/Tests/Database/LocalDatabaseTest.php#L51`)

In a second step, doctrine DBAL stuff should be used.

**Comment by vertexvaar** [comment]
Since we support always both active LTS version we still have to support TYPO3_DB. This means that as long as 7.6 is LTS we will continue using TYPO3_DB and when TYPO3 v9 is released we will completely switch to doctrine DBAL. Supporting both is not possible.
