### ISSUE TITLE
[BUG] file moved and content replaced, only moved on page publish (if referenced)

### ISSUE THREAD

**Issue by AndreasA** [in2code-de/in2publish_core#28]
Hi, in regards to my file issue I think I now know how to replicate it exactly:

1.) Upload a file to a fileadmin folder, e.g. fileadmin/uploads01/
2.) Reference the file in a content element
3.) Publish the page with the content element
4.) Move the same file to another folder in fileadmin, e.g. fileadmin/uploads02/
5.) Replace that file with another file (upload and select replace)
6.) Go the same page of step 3 and publish the page.

Now the page content is published and the file was moved BUT the content was not updated.
That requires another publish of the page (it is also marked as still having changes).

**Comment by vertexvaar** [comment]
I was able to reproduce this bug. in2publish thinks this file was just moved and does not have a look at the file size or other properties anymore. When publishing for the second time the file will be checked for file size / content differences because it was not changed otherwise.

**Comment by vertexvaar** [comment]
It was a kind of nightmare, but I managed it somehow. Hope this finally fixes the whole problem.
