### ISSUE TITLE
Category relations missing when publishing file

### ISSUE THREAD

**Issue by holgerkraemer** [in2code-de/in2publish_core#35]
- Upload file and attach categories
- Publish this file via backend-module
- In the foreign DB, the category-relations ("sys_category_record_mm") to this file are missing 
  (while "sys_file_metadata"-records related to this file seem to be synced correctly)

**Comment by vertexvaar** [comment]
Hi @holgerkraemer 

i can reproduce this issue only with the Workflow Feature from the enterprise edition in2publish. Either use the issue tracker for the enterprise version at https://projekte.in2code.de/ if you work for a client which has bought that edition (limited support is included)
*or* - if you don't use in2publish, just in2publish_core - double check everything (especially the factory.*recursion settings), check the logs and provide more information about your system and settings.

**Comment by vertexvaar** [comment]
This issue has been transferred to https://projekte.in2code.de/issues/27207
