### ISSUE TITLE
[FEATURE] preview: Override domain / scheme (x-frame settings)

### ISSUE THREAD

**Issue by AndreasA** [in2code-de/in2publish_core#37]
My local domain uses http and the foreign https. I have a redirect in place to https so it isn't that big a deal but it would be nice if the preview module could use the correct scheme.

Also my default domain which is publicly available adds x-frame options to the header to avoid it being used on other sites as iframe.

In order to "fix" this one solution would be to use a second internal only domain but that one cannot be the first domain.

**Comment by vertexvaar** [comment]
Hi @AndreasA 

> it would be nice if the preview module could use the correct scheme

This is an issue based on the same problem of a bug i once discovered in RealUrl. The quintessence is, that we are not able to reliably detect the protocol which should be used for which domain, so we are on the safest side to just assume that they both are accessed from either HTTP or HTTPS. This can't be changed. (But there's a possibility. See next paragraph)

> my default domain which is publicly available adds x-frame options to the header

This case is currently not supported. You could set `X-Frame-Options: ALLOW-FROM http://stage.mydomain.com/` but be aware that this will disclose your Local instance's domain.

The only reliable solution which comes to my mind is (in2publish) configuration. Only configuration is flexible enough to define domains and protocols per page for the page tree (global or PageTS). The current state of configuring in2publish(_core) would require every user to update their config, so we hesitate to introduce new options. I will discuss this topic with the PO, so this option might be available some day.

I'm sorry there is no way to solve this issue nicely, but you can XCLASS the `CompareUriViewHelper` which will be introduced in the upcoming version 5.10.0 for the compare-view URL and the template of the compare view or `GetFirstDomainFromRootlineViewHelper` for the domains of each staging instance.

**Comment by AndreasA** [comment]
Wha about making the setting optional? Use the first domain if not set, otherwise use the setting?

**Comment by vertexvaar** [comment]
All configuration values of in2publish_core are required, the current configuration evaluation does not allow for optional keys. This behaviour won't be changed until the configuration overhaul, which has been discussed with the PO long time ago, but that didn't pass the state of a concept. The PO is very... hesitant with assignment of such things. (I'm sorry i can't do anything for you in this particular case).

**Comment by AndreasA** [comment]
No problem. I overrode the Template and added a configuration option using the SignalDispatcher for the page comparison domain.
Thanks for your help so far.
