### ISSUE TITLE
"Inspect TCA" not working

### ISSUE THREAD

**Issue by josefglatz** [in2code-de/in2publish_core#39]
# Problem

* click on 
![image](https://user-images.githubusercontent.com/2861556/29525638-a4fc315c-8693-11e7-8037-4904e4b04fd1.png) 
* throws error: 

> Class 'In2code\In2publishCore\Domain\Service\TcaService' not found

## Environment

* TYPO3 8.7
* in2publish_core dev-master
* in2publish dev-master

**Comment by vertexvaar** [comment]
Thank you for reporting 👍
