### ISSUE TITLE
FAL Relations from fluidcontent/flux elements are not resolved

### ISSUE THREAD

**Issue by dr-bock** [in2code-de/in2publish_core#44]
FAL Relatations from fluidcontent / flux Custom-Content-Elements are not resolved.

Problem is your commit 314ca8b3 with description "[BUGFIX] Do not directly resolve relations from pages to sys_file_reference".
Because FAL-References from flux content-elements are identifierd by pid and identifier and are not stored in the tt_content record.

Testet with latest in2publish-Version and flux 8.2.1 (latest stable master)

**Comment by sbusemann** [comment]
Hi Nikolaj,
the data structure of fluidcontent / flux is currently not supported. We maintain all structures which are coming from the TYPO3 core (and in the mean time of some additional extensions). If you need the support, you can contribute by a pull request or we can create you an offer to support that feature. Feel free to contact me in person.
