### ISSUE TITLE
SSH Connection with Passphrase seems to be buggy

### ISSUE THREAD

**Issue by einpraegsam** [in2code-de/in2publish_core#45]
We digged into that issue in in2code Ticket https://projekte.in2code.de/issues/29530

I tested it locally. Added a new Private/Pubkey pair with passphrase. A short test in console worked (after adding the new PubKey to authorized_keys). 
After that, publishing tests in backend module always failed to connect to localhost.

<img src="https://s.nimbus.everhelper.me/attachment/1397155/c0iy29lhtqoxr31s0ov3/262407-6Cc14rvS4pU9naue/screen.png" />

In YAML I tried:
```
sshConnection:
    privateKeyPassphrase: 'passphrase'
```
(With ", with ' and without)

**Comment by vertexvaar** [comment]
As it turned out in2publish_core works as expected.
PHP's SSH2 extension just does not support ed25519 keys as documented in http://php.net/manual/de/function.ssh2-auth-pubkey-file.php

**Comment by einpraegsam** [comment]
You just closed this issue because of something that is wrong documented on php.net. This is maybe a bit disturbing for the customer. What should we tell her? There is no possibility to use Private Keys with Passphrase?
BTW: That feature was never tested before?

**Comment by vertexvaar** [comment]
No.
1) The documentation on php.net is correct. ext-ssh2 simply does not support other keys than RSA.
2) I'm using an encrypted RSA key in my local development so it is very well tested.
3) The specific customer already knows that he can only use RSA.
4) The documentation of in2publish_core suggests generating a default key which is RSA
5) Using RSA keys with passphrases is not only tested very well but is also available as option, so it is actively supported.

**Comment by einpraegsam** [comment]
Thx for clarifying
