### ISSUE TITLE
Wrong links in TYPO3 documentation

### ISSUE THREAD

**Issue by einpraegsam** [in2code-de/in2publish_core#46]
Mail from our contact form:
```
Guten Tag,

auf https://docs.typo3.org/typo3cms/extensions/in2publish_core/ funktionieren die Links zu Documentation und Requirements And Limitations nicht. Gibt es alternative Links oder können Sie die Links korrigieren?

Vielen Dank```

**Comment by sbusemann** [comment]
Seems that docs.typo3.org is quicker and more intelligent, then we think. The Dead link is taken from GitHub, where the master documentation is shown. I guess, with next release the problem will be solved.
