### ISSUE TITLE
DB test fails when port is not 3306 

### ISSUE THREAD

**Issue by YKWeyer** [in2code-de/in2publish_core#48]
When using a port other than 3306 to access foreign database, the `tests` view returns
> One or more options are not confiured correctly.
> [foreign.database.hostname]: The host [HOST] is not reachable: Host is unreachable

This error probably results of the CoreDefiner testing the foreign database hostname on port 3306 (hardcoded):
https://github.com/in2code-de/in2publish_core/blob/55bfcb076eabb4c2a8dae8b4cda4194e3a33875a/Classes/Config/Definer/In2publishCoreDefiner.php#L147

### Possible fixes
The test should retrieve the port value from the custom configuration, or be defined as non-blocking for other tests to run

**Comment by sbusemann** [comment]
https://projekte.in2code.de/issues/32520

**Comment by vertexvaar** [comment]
Hi @YKWeyer,

the `HostNameValidator` has been removed by @sbusemann, as it will be tested with the actual port in the `DatabaseConnectionTest`. Thank you for your report :+1:
