### ISSUE TITLE
Allow usage of nav_title in Record Index View

### ISSUE THREAD

**Issue by d3pendent** [in2code-de/in2publish_core#49]
The Partial `/Record/Index/PageList.html` uses a Viewhelper `<publish:Miscellaneous.GetPropertyFromStagingDefinition record="{record}" propertyName="title" stagingLevel="local" />` 
The propertyName is set to `title` without the ability to change that.

It would be nice if it could be configured to use the nav_title. This way it would match the page tree if you also have the nav_title displayed there.

**Comment by sbusemann** [comment]
https://projekte.in2code.de/issues/32521

**Comment by sbusemann** [comment]
This is released
