### ISSUE TITLE
TYPO3 Database Connection expects array, string given

### ISSUE THREAD

**Issue by pixelbrackets** [in2code-de/in2publish_core#56]
> Argument 1 passed to TYPO3\CMS\Core\Database\DatabaseConnection::setInitializeCommandsAfterConnect() must be of the type array, string given, called in in2publish_core/Classes/Utility/DatabaseUtility.php on line 71

The method [getDatabaseInitializationCommands](https://github.com/in2code-de/in2publish_core/blob/develop/Classes/Service/Environment/ForeignEnvironmentService.php#L69-L106) generates those commands by decoding some base64 values. The result however may be a string on some cases.

**Comment by vertexvaar** [comment]
Hi @pixelbrackets,

nice to see you here :wink: 
In version 8.0 of in2publish_core we changed the complete code base to switch from TYPO3 Database Connection to Doctrine DBAL, therefore this issue does not apply anymore to the current develop.

If you still require this change in an older version (becaue you are using TYPO3 or older) you can contact me for a merge strategy (TYPO3 Slack or so).

With Best Regards
