### ISSUE TITLE
[BUG] Could not open input file: ./../vendor/bin/typo3

### ISSUE THREAD

**Issue by tmilitaru** [in2code-de/in2publish_core#58]
Since the CLI endpoint changed to ./vendor/bin/typo3 - we cannot pass the tests in TYPO3 9.5.5, we get the error message: 
```
Could not call the CLI dispatcher on foreign because of an unexpected error.
The call to the dispatcher returned following message:
Could not open input file: ./../vendor/bin/typo3
```
I didn't find anything about this in the documentation.
TYPO3 9.5.5 (installed without composer)
in2publish_core - 8.0.0
in2publish - 8.0.0

**Comment by vertexvaar** [comment]
Hi @tmilitaru,

did you configure the `foreign.rootPath` path to the document root (where the index.php is)?
Or did you even alter the document root for TYPO3 in your composer.json?

**Comment by tmilitaru** [comment]
Hi @vertexvaar , 
rootPath is configured and TYPO3 is not installed via composer

**Comment by vertexvaar** [comment]
Hi @tmilitaru,

sorry i overlooked that you wrote "**without** composer". TYPO3 does ship all vendor libraries in the `vendor` folder but not the `vendor/bin` directory which is also generated by composer (which is used to manage the dependencies).
I will check and discuss the options for the non-composer installation support with the product owner next week. Please stay tuned.

**Comment by vertexvaar** [comment]
@tmilitaru as long as this is not fixed you can symlink or copy the file `public/typo3/sysext/core/bin/typo3` to `vendor/bin/typo3` as a workaround

**Comment by tmilitaru** [comment]
@vertexvaar I tried with a symlink, however I get problems with require (2 levels too up):
`PHP Fatal error:  require(): Failed opening required '/var/www/typo3/sysext/core/Configuration/DefaultConfiguration.php'`

I don't think it's that easy.

**Comment by vertexvaar** [comment]
Oh well, that's somewhat strange (and obvious at once, knowing there is a `typo3-cli` package) that TYPO3 is using a different file now.
Remove the symlink and create the file `vendor/bin/typo3` with the content:
```
#!/usr/bin/env php
<?php
/*
 * This file is part of the TYPO3 CMS project.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */
call_user_func(function() {
    $classLoader = require __DIR__ . '/../autoload.php';
    \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::run(1, \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::REQUESTTYPE_CLI);
    \TYPO3\CMS\Core\Core\Bootstrap::init($classLoader)->get(\TYPO3\CMS\Core\Console\CommandApplication::class)->run();
});
```

That should work.

**Comment by tmilitaru** [comment]
Thanks for the suggestion, unfortunately it still doesn't work:
`PHP Fatal error:  require(): Failed opening required '/var/www/html/project/typo3_src/vendor/typo3/sysext/core/Configuration/DefaultConfiguration.php' in /var/www/html/typo3_src-9.5.3/typo3/sysext/core/Classes/Configuration/ConfigurationManager.php on line 92`
This is when I try to call it myself from command line. 
From in2publish tests, I still get:
`Could not open input file: ./../vendor/bin/typo3`
To make sure we are on the same page, I created it in: 
`<project-root-folder>/vendor/bin/typo3`

**Comment by vertexvaar** [comment]
This issue is accepted as it already has an internal ticket.

**Comment by tmilitaru** [comment]
@vertexvaar thank you! Do you know if it will be released this month?

**Comment by vertexvaar** [comment]
Hi @tmilitaru 

i am confident that we will publish a maintenance release this month.

**Comment by tmilitaru** [comment]
@vertexvaar - I tested the fix, however during tests I get:
`The requested envelope is not available`

I think the problem is that the IN2PUBLISH_CONTEXT is not set in the command call and it's always "Foreign",  so Letterbox->receiveEnvelope connects incorrectly to local database instead of foreign. 
Is this possible?

**Comment by vertexvaar** [comment]
@tmilitaru nah, even if the `IN2PUBLISH_CONTEXT` is not set it will default to `Foreign` and connect to the DB on foreign (which is "local" on foreign, because it is the default DB for the TYPO3 instance), which is correct. in2publish_core writes and reads envelopes exclusively to and from the foreign database.
This looks like a different problem. Can you truncate all in2publish related tables, clear all caches and try again? If the problem persists, please open a new issue.

**Comment by emdria** [comment]
Still not working in version 9.5.19 - any news on this?
