### ISSUE TITLE
Backend module not showing up

### ISSUE THREAD

**Issue by MichaelPerlbach** [in2code-de/in2publish_core#6]
Hi,

I installed "in2publish" on a TYPO3 7.6.14 for a stage and a live environment and made all the necessary configuration steps. Until now, the backend module "Publish Tools" is not showing up - and no information is given anywhere what I might have done wrong. Is there any way to get helpful information about how to fix this?

Regards
Michael

**Comment by einpraegsam** [comment]
Hi, did you set the environment variable? See https://github.com/in2code-de/in2publish_core/blob/master/Documentation/Installation/Preparation.md#os-requirements

**Comment by MichaelPerlbach** [comment]
Yes, I did that. But it did not help.

**Comment by einpraegsam** [comment]
As far as I remember, the backend modules will show up if:
- The environment variable is set correct to Local "SetEnv IN2PUBLISH_CONTEXT Local" - please double check this
- The extension is installed and loaded
- The cache was cleaned

**Comment by MichaelPerlbach** [comment]
I triple-checked this.
I found the problem - it is not allowed to use SetEnv on Domainfactory. I will try to use the PHP function "putenv". Maybe that works.

**Comment by MichaelPerlbach** [comment]
Hi,

FYI: using "putenv()" works like charm :-)
simply put the following lines in the first line of TYPO3's "LocalConfiguration.php":
Local: putenv('IN2PUBLISH_CONTEXT=Local');
Foreign: putenv('IN2PUBLISH_CONTEXT=Foreign');

Case closed.

**Comment by einpraegsam** [comment]
Thx for your final feedback to this issue!
