### ISSUE TITLE
Support of »file_reference« in records

### ISSUE THREAD

**Issue by pixelbrackets** [in2code-de/in2publish_core#69]
Hey Hey,

Release 7.3.0 has this nifty feature: »[FEATURE] Support file_reference used by flux for file relations«. Is this for flexforms only?

When I run the TCA inspection in the »Publish Tools« module and check for the same structure on a table with an image field of `[type] => group` and `[internal_type] => file_reference` I get the following error message: `The internal type "file_reference" is not supported`.

Since it works with flexforms I see no reason why I shouldn’t work with other regular TCA fields (besides of that both internal types `file` & `file_reference` are deprecated). So I overwrite the group processor and voilà »file_references« in those records get published as well.

Shall I send a PR?

**Comment by vertexvaar** [comment]
Hi @pixelbrackets,

sorry for the exceptional delay.
A PR would be very welcome.

**Comment by pixelbrackets** [comment]
> Hi @pixelbrackets,
> 
> sorry for the exceptional delay.
> A PR would be very welcome.

I've rebased the patch and send a PR for develop (TYPO3 9 & 10) and TYPO3-v8 (TYPO3 8).
