### ISSUE TITLE
TYPO3 Exception Class 'Backend Test' not found

### ISSUE THREAD

**Issue by grexen** [in2code-de/in2publish_core#70]
After publishing, I get an error message that the Class 'Backend Test' was not found:

<br/>Uncaught TYPO3 Exception Class 'Backend Test' not found<br/>thrown in file /var/www/html/typo3/web/typo3/sysext/core/Classes/Utility/GeneralUtility.php<br/>in line 3667<br/><br/>

Publishing still works.

I'm using Typo3 9.5.7 and in2publish 8.1.1

**Comment by vertexvaar** [comment]
Hi @grexen ,

sorry for the exceptional delay. I think you probably solved the problem already :sweat_smile: 

For everyone else that stumbles over this Problem: Truncate the Table `tx_in2code_in2publish_task`
