### ISSUE TITLE
Exception when using ###PAGE_TSCONFIG_ID### in foreign_table_where

### ISSUE THREAD

**Issue by typecat** [in2code-de/in2publish_core#72]
Use case:
I have a custom tt_content field to select records from a custom table. As it is a multi page tree installation, there needs to be a limitation of the custom table record's pid per page tree. I did this according to the TYPO3 docs by 
`'foreign_table_where' => 'AND tx_myextension_domain_model_record.pid = ###PAGE_TSCONFIG_ID### `
on the custom tt_content field 'myextension_record' and setting it via
`TCEFORM.tt_content.myextension_record.PAGE_TSCONFIG_ID = 3`

The publish overview throws and exception if my content element using this field exists on the page to publish:

> Oops, an error occurred!
>An exception occurred while executing 'SELECT * FROM `tx_myextension_domain_model_record` WHERE (`uid` LIKE ?) AND (tx_myextension_domain_model_record.pid = #PAGE_TSCONFIG_ID AND tx_myextension_domain_model_record.hidden = 0 AND tx_myextension_domain_model_record.deleted = 0) ORDER BY `crdate` ASC' with params ["1"]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

I was curious, why marker hashes seem to be missing in the query and found following replacement in in2publish_core/Classes/Domain/Service/ReplaceMarkersService.php → replaceGeneralMarkers

```
$string = str_replace(
            [
                '###THIS_CID###',
                '###SITEROOT###',
                '###PAGE_TSCONFIG_ID###',
                '###PAGE_TSCONFIG_IDLIST###',
                '###PAGE_TSCONFIG_STR###',
            ],
            [
                0,
                '#_SITEROOT',
                '#PAGE_TSCONFIG_ID',
                '#PAGE_TSCONFIG_IDLIST',
                '#PAGE_TSCONFIG_STR',
            ],
            $string
);
 return $string;
```

Why is this done? Is this an intentional error/ missing feature? Or is there something wrong in my configuration?

Using:
- TYPO3 9.5.13
- in2publish_core 8.4.5

**Comment by vertexvaar** [comment]
Hi @typecat :wave: 

these marker substitutions are actually not implemented, because there has been no requirement since the content publisher exists (> 5 years).
The content publisher logs (database) should also tell you that: `Marker replacement not implemented`.
Since TYPO3 supports these we have support them. I just need to implement it :wink:

**Comment by typecat** [comment]
Hi @vertexvaar 
I see there was a [new release](https://github.com/in2code-de/in2publish_core/releases/tag/8.5.0) is this feature covered there already? If not, when do you plan to add it? This missing feature is currently blocking our customer to publish a lot of pages.
