### ISSUE TITLE
No page translation possible if publishing a new language

### ISSUE THREAD

**Issue by typecat** [in2code-de/in2publish_core#75]
What I intended to do:

Add a new language (sys_language) and create a new translation in that language of a page (doktype 254) outside a site.
The page tree looks as following:
[0]
- General storage (doktype 254)
- Site 1 with site configuration
- Site 2 with site configuration

What did I do:

1. Created a new language on stage system on page 0
2. Created a translation in the new language of the "General storage" page
3. Published both new language and new translation to production system

What did I expect:

Both the new language and the new translation to appear on production system

What happened instead:

Only the new language is visible on the production system. The translated page record is, thus present in the database, not visible in the TYPO3 backend.

I re-created this problem on a test environment. There I only published the new language. I would have expected, that it would be possible to crate a new translation in that language on the production system, but it isn't. Then I crated a second new language directly on the production system and both languages were available for translation.
It seems as if there are some processes triggered by TYPO3 when crating a new language by hand that don't happen if crating a new language by publishing. Any ideas how to solve this?

Technical factors:
TYPO3: 9.5.17
EXT:in2publish_core 9.0.0

**Comment by vertexvaar** [comment]
Hi @typecat,

first of all, please update to the latest in2publish_core version (currently 9.0.2). In 9.0.1 a bug was fixed which would not show certain pages in the Publish Overview Module.

I could actually reproduce the behavior when publishing a folder outside of a page tree with a site. Choosing the folder on foreign with the page or list module  did throw an exception but after clearing the system caches the folder was accessible. Also, the translation became visible.
In search of more answers i debugged through the DataHandler but found no place where the creation of a page would trigger something that could explain this behavior. It seems that this is limited to caching.

BTW: It seems that in TYPO3 v10 it is not possible to "translate" a sys folder which is not in a site.

**Comment by typecat** [comment]
Thank you @vertexvaar!
An update to 9.0.2 solved the issue! Next time I'll try an update first, even if the change log doesn't seem to contain a solution ;)
