### ISSUE TITLE
Improve Error Message for Slow Filesystem Check

### ISSUE THREAD

**Issue by pixelbrackets** [in2code-de/in2publish_core#80]
The latest version of in2publish_core includes a check for slow file systems.

This error message only shows the current value. It should also show the expected value. Otherwise the integrator has now idea what “slow” means.

Also: This check leads to an error. It should be a warning imho and continue with other checks. Could you explain why this is considered an error? The message itself sounds more like a nice-to-have thing.

![publisher-test-errors](https://user-images.githubusercontent.com/1592995/91064801-08e0f280-e630-11ea-9e04-371ccbd7e1ae.png)

**Comment by pixelbrackets** [comment]
> Also: This check leads to an error. It should be a warning imho and continue with other checks.

Just saw that the check has a severity OK from 0-0.06, WARNING for 0.06-0.08 and ERROR for > 0.08. I'm not sure why this threeshold is an error however.

**Comment by typecat** [comment]
PS: This is on TYPO3 9.5.20 with EXT:in2publish_core 9.1.0

As far as I can see there are not changes related to performance compared to EXT:in2publish_core 9.2.0
