### ISSUE TITLE
DiskSpeed perfomance tests fail on DV / ST environments

### ISSUE THREAD

**Issue by tmilitaru** [in2code-de/in2publish_core#82]
Usually the development & staging environments are slower than PR & we use the Tests from in2publish in our deployment workflows, deployment is blocked because tests fail if the read / write speed is not as hardcoded values in tests.

This could be solved by allowing the parameters to be user defined in the configuration.
Currently:
```php
protected const THRESHOLD = [
        'read' => [
            TestResult::OK => 0.03,
            TestResult::WARNING => 0.04,
        ],
        'write' => [
            TestResult::OK => 0.06,
            TestResult::WARNING => 0.08,
        ],
    ];
```

**Comment by vertexvaar** [comment]
Duplicate of #80
