### ISSUE TITLE
TypeError when publishing Content Elements with linked Files in RTE

### ISSUE THREAD

**Issue by dr-bock** [in2code-de/in2publish_core#87]
System:
in2publish_core v10
TYPO3 v10.4.21
PHP 7.4.24
MySQL 8.0.23

Scenario:
E.g. normal text content element. bodytext. Set a link to a file in the RTE. Try to publish the element / the page.

Output:
`Argument 1 passed to In2code\In2publishCore\Domain\Repository\CommonRepository::findByIdentifier() must be of the type int, string given, called in /var/www/html/project/public/typo3conf/ext/in2publish_core/Classes/Domain/Repository/CommonRepository.php on line 673`

**Comment by vertexvaar** [comment]
Cleaning up stale issue
