### ISSUE TITLE
Performance tests use inconsistent units

### ISSUE THREAD

**Issue by YKWeyer** [in2code-de/in2publish_core#88]
I just noticed the units used in performance tests are not consistent. Results in `ms` (milliseconds) in the content are also written as `microseconds` in the title of at least the FS and DB-Test

![image](https://user-images.githubusercontent.com/1093360/155708948-1b8e5227-5825-4066-a3cc-b3766845d33a.png)

![image](https://user-images.githubusercontent.com/1093360/155709465-4e42f7e1-0402-4314-a8b8-1a58271bdda3.png)

This looks like a wording issue, the title should probably say "milliseconds"

**Comment by tinzog** [comment]
The issue has been resolved with the merge request
https://github.com/in2code-de/in2publish_core/commit/e5dd207989556a3eeaa7b08d3c714672964c8271
