### ISSUE TITLE
Remove tx_in2code_in2publish_envelope from defaultIgnoredTables

### ISSUE THREAD

**Issue by metapublic-gbr** [in2code-de/in2publish_core#92]
The backend test of in2publish_core gives a warning that table tx_in2code_in2publish_envelope defined in excludeRelatedTables does not exist. The table is not present since it is not used in newer versions of in2publish_core. Unfortunately the entry is still set in \In2code\In2publishCore\Config\Definer\In2publishCoreDefiner::$defaultIgnoredTables and added to the locally configured array.

Could you please remove the entry from the defaults to get rid of the warning?

Thank you
Andreas

**Comment by sbusemann** [comment]
We will check it.

Internal issue number: 57470

**Comment by tinzog** [comment]
This issue has been resolved with Commit afcc2c04 ([FIX] Corrects ignoredTable Definition) and is available from version 11.0.7
